src/Entity/Questions.php
<?php

namespace App\Entity;

use App\Repository\QuestionsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: QuestionsRepository::class)]
class Questions
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Label = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $img = null;

    #[ORM\OneToMany(mappedBy: 'questions', targetEntity: Answers::class)]
    private Collection $answers;

    public function __construct()
    {
        $this->answers = new ArrayCollection();
    }

    // Permet de transformer une entité en chaine de caractère
    public function __toString()
    {
        return $this->Label;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLabel(): ?string
    {
        return $this->Label;
    }

    public function setLabel(string $Label): self
    {
        $this->Label = $Label;

        return $this;
    }

    public function getImg(): ?string
    {
        return $this->img;
    }

    public function setImg(?string $img): self
    {
        $this->img = $img;

        return $this;
    }

    /**
     * @return Collection<int, Answers>
     */
    public function getAnswers(): Collection
    {
        return $this->answers;
    }

    public function addAnswer(Answers $answer): self
    {
        if (!$this->answers->contains($answer)) {
            $this->answers->add($answer);
            $answer->setQuestions($this);
        }

        return $this;
    }

    public function removeAnswer(Answers $answer): self
    {
        if ($this->answers->removeElement($answer)) {
            // set the owning side to null (unless already changed)
            if ($answer->getQuestions() === $this) {
                $answer->setQuestions(null);
            }
        }

        return $this;
    }
}

src/Controller/QuizController.php
<?php

namespace App\Controller;

use App\Entity\Questions;
use App\Entity\Answers;
use App\Enity\Results;
use App\Repository\QuestionsRepository;
use App\Repository\AnswersRepository;
use App\Repository\ResultsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\Routing\Annotation\Route;


class QuizController extends AbstractController
{
    //clear session in case of restart the quiz
    #[Route('/quiz', name: 'app_quiz_start')]
    public function initiate(RequestStack $requestStack) : Response
    {
        $session = $requestStack->getSession();
        $session->set('question', []);

        return $this->redirectToRoute('app_quiz_question', [
            'questions_id' => 1
        ]);
    }

   //homequiz
    #[Route('/home', name: 'app_quiz_home')]
    public function index(): Response
    {
        return $this->render('quiz/homequiz.html.twig', [
            'controller_name' => 'QuizController',
        ]);
    }
    //how to
    #[Route('/tutoquiz', name: 'app_quiz_tuto')]
    public function tuto(): Response
    {
        return $this->render('quiz/tutoquiz.html.twig', [
            'controller_name' => 'QuizController',
        ]);
    }

     

    
    //define Route to question
    #[Route('/quiz/{questions_id}', name: 'app_quiz_question')]
    public function question($questions_id, QuestionsRepository $questionsRepository , RequestStack $requestStack): Response
    {
   

        // get answers by question ID
       $question = $questionsRepository -> findOneById($questions_id);

   
       return $this->render('quiz/index.html.twig', [
            'question' => $question
        ]);

    }

    //define Route for saving answers
    #[Route('/quizsave', name: 'app_quiz_save')]

    //iniate storage in session
    public function saveQuestion(RequestStack $requestStack, Request $request): Response
    {
        //retry the result of the previous page
        $session = $requestStack->getSession();

        //dd($session->get('question'));
        $tab = $session->get('question');
        /// create tab to store question and answers values
        if($tab == null){
            $tab = [];
        }

        //dd();
        //push new values in the array
        array_push($tab, [$request -> request->get('id_question'), $request -> request->get('id_answer')]);

        //dd($tab);
        $session->set('question', $tab);

        // allow to return to next question of id isn't 10, otherwise, go next 
        //$question = $questionsRepository -> findOneById($questions_id); 

        //if there is less than 10 questions, return to the next question
        //dd($tab);
        if(count($tab) <10){

            //to show next question if it is under 10
            $q = count($tab)+1;
        
            //to show next question if it is under 10
            return $this->redirectToRoute('app_quiz_question', [
                'questions_id' => $q
            ]);
            }
            //otherwise got to the result
            else {
                return $this->redirectToRoute('app_quiz_result', [
                    
                ]);
            }  
            
    }

     //define Route for results
     #[Route('/quizresult', name: 'app_quiz_result')]

     //unicorn because this is the "touchiest" function
     public function getLicorneResult (ResultsRepository $resultsRepository,AnswersRepository $answersRepository,RequestStack $requestStack, Request $request): Response
     {
        // retry final tab result 
        $session = $requestStack->getSession();
        $tab = $session->get('question');
        $resultFinal=0;
        $question='';
        //dd($tab);

        //retry value per answer id

        foreach ($tab as $row) {

            $row[1];
            //dd($row[1]);
            $result = $answersRepository -> findOneById($row[1]);
            $resultFinal += $result -> getValue();
        };
        
        //dd($resultFinal);

        //display relevant profile and push it
        $finalResult=$resultsRepository -> findResultDescription($resultFinal);
        return $this->render('quiz/result.html.twig', [
            'result' => current($finalResult)
        ]);
        //dd($finalResult);
        
   
     
     
}
}

templates/quiz/homequiz.html.twig
{# {% extends 'base.html.twig' %} #}

{% block title %}Accueil quiz{% endblock %}

{% block stylesheets %}

    <link rel="stylesheet" href="{{asset('/assets/css/quiz/homequizbis.css')}}">   
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="css/reset.css">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

{% endblock %}

{% block body %}

<main>
        <div class="container-fluid backgroundhomequiz">
            <div class="d-flex justify-content-end">
                <a id="direct" href={{path('app_home')}}><i>Je me rends directement sur le site</i><img src="/assets/img/iconesQuiz/icone-porte/icon-porte-defaut.svg" alt="iconeporte"></a>
            </div>
            <div class="container">
                <div class="text-center">
                    <img class="img-fluid" id= "logoquiz" src="/assets/img/logoquiz/logo-bullee-grand.svg" alt="logo">
                </div>

                <div class="row text-center" id="txthomequiz">
                    <div class="col-lg-5 col-sm-10">
                        <p>Bullee te propose un quiz afin de t'aider à savoir comment tu te comportes avec tes copains.</p>
                        <a class="bouton text-center" href={{path('app_quiz_tuto')}}>Je commence le quiz</a> 
                    </div>

                    <div class="offset-2 col-5">
                        <img id="imghomequiz" src="/assets/img/illustrationquizz/illustration-BULLEE.svg" alt="">

                    </div>
                </div>     
            </div> 
        </div>
</main>

{% endblock %}
 

templates/quiz/index.html.twig
{# {% extends 'base.html.twig' %} #}

{% block stylesheets %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

  <link rel="stylesheet" href="{{asset('/assets/css/reset.css')}}">
    <link rel="stylesheet" href="{{asset('/assets/css/quiz/questionsbis.css')}}"> 
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>  
{% endblock %}

{% block body %}
<main>
        <div class="container-fluid backgroundmiseensituation">
            <div class="d-flex justify-content-end">
                <a class="quitter" href={{path('app_home')}}><img src="/assets/img/iconesQuiz/fab-quitter-white.svg" alt="quitter"></a>
            </div>

            <div class="d-flex test">
                

                <img class="cadreimage" src="/assets/img/{{ question.img }}" alt="question.img" >

                <section id="sectionquestions">
                  
                    <h3 id="question" class="text-center"> "{{ question.label }}"</h3>

                    <div class="reponses text-center d-flex flex-column">
        
                        <form method="post" id="formQuiz" action={{path('app_quiz_save')}}>

                            <input type="hidden" name="id_answer" id="data" value="">
                            <input type="hidden" name="id_question" value="{{ question.id }}">

                             {% for answer in question.answers %}
                            <input type="radio"  class="radioreponse"> <label class="answ" data-id="{{ answer.id }}" for="reponse" >{{ answer.label }}</label>
                           
                            {% endfor %}
                            
                          <button method="" type="button" id="btnvalidform" class="questionsuivant bouton" name="clicked">Suivant</buton>
                        
                           
                        </form>
                        
                    </div>
                </section>

            </div>

        </div>

    </main>

{% endblock %}
{% block javascripts %}
    <script type="text/javascript" src="/assets/js/index.js"></script>
 {% endblock %}

templates/quiz/result.html.twig
{% block stylesheets %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="css/reset.css">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <link rel="stylesheet" href="/assets/css/quiz/resultat.css">
{% endblock %}
{% block body %}
<main>
        <section>
             <!-- icone retour--> 
            <div class="container-fluid">
            <div class="retour">
                <a href={{path('app_quiz_home')}}><img src="/assets/img/iconesQuiz/fab-retour.svg" alt=""><h3 id="titre">Refaire le quiz</h3></a>
            </div>

             <!-- Bloc de texte--> 
        </div>
            <div class="offset-lg-1 col-lg-4 encadrer">
                
                <p>{{ result.description|raw}}</p>
            </div>
    
            <div>
                <img id="grande" src="/assets/img/bullesQuiz/bulle-grand-transparent.svg" alt="">
                <img id="moyen" src="/assets/img/bullesQuiz/bulle-moyen-transparent.svg" alt="">
                <img id="petite" src="/assets/img/bullesQuiz/bulle-petit-transparent.svg" alt="">
                <img class="bulleesize" src="/assets/img/bulle.png" alt="bullee">
            </div>
            
            <a class="bouton text-center" href={{path('app_home')}}>Je découvre Bullee</a>
        </section>
    </main>
 {% endblock %}

templates/quiz/tutoquiz.html.twig
{# {% extends 'base.html.twig' %} #}

{% block title %}Tuto du quiz{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{asset('/assets/css/quiz/tutoquizbis.css')}}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="reset.css">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    
{% endblock %}

{% block body %}
<main>

        <div class="container-fluid backgroundtutoquiz">
            <div class="d-flex justify-content-end">
                <a id="direct" href={{path('app_home')}}><i>Je me rends directement sur le site</i><img src="/assets/img/iconesQuiz/icone-porte/icon-porte-defaut.svg" alt="iconeporte"></a>
            </div>
            
            <div class="d-flex text-center justify-content-center align-items-center">
                <section id="tuto">
                    <div>
                        <p>En lançant ce quiz, des illustrations vont te mettre face à des situations pouvant faire partie du quotidien.</p>
                        <p>Prends le temps de regarder les scènes et de comprendre ce qu’il s’y passe.</p>
                        <p>Une fois l’image observée, à toi de décider comment tu réagirais parmi 4 propositions.</p>
                    </div>
                    <a class="bouton text-center" href="{{path('app_quiz_start')}}">Je commence le quiz</a> 
                </section>

            </div>

        </div>
           
    </main>
<div>

{% endblock %}